version: "3"

services:
  express:
    build: ./express
    image: api-benchmarks/express
    ports:
      - 3000:3000

  flask:
    build: ./flask
    image: api-benchmarks/flask
    ports:
      - 3001:5000

  fastify:
    build: ./fastify
    image: api-benchmarks/fastify
    ports:
      - 3002:3000

  koa:
    build: ./koa
    image: api-benchmarks/koa
    ports:
      - 3003:3000

  node:
    build: ./node
    image: api-benchmarks/node
    ports:
      - 3004:3000
